# Generated by Django 6.0.3 on 2026-03-11 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=4)),
                ('ciudad', models.CharField(max_length=80)),
                ('estadio', models.CharField(max_length=100)),
                ('capacidad_estadio', models.PositiveIntegerField(default=30000)),
                ('color_principal', models.CharField(default='#FFFFFF', max_length=7)),
                ('color_secundario', models.CharField(default='#000000', max_length=7)),
                ('presupuesto_fichajes', models.PositiveIntegerField(default=10000000)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('temporada', models.CharField(max_length=20)),
                ('jornadas_totales', models.PositiveSmallIntegerField(default=38)),
                ('jornada_actual', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('nacionalidad', models.CharField(max_length=60)),
                ('edad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(45)])),
                ('posicion', models.CharField(choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Centrocampista'), ('DEL', 'Delantero')], max_length=3)),
                ('pie_dominante', models.CharField(choices=[('D', 'Derecho'), ('I', 'Izquierdo'), ('A', 'Ambidiestro')], default='D', max_length=1)),
                ('dorsal', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('velocidad', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('regate', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('disparo', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pase', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('defensa', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fisico', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('porteria', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('salario', models.PositiveIntegerField(default=500000)),
                ('temporadas_contrato', models.PositiveSmallIntegerField(default=2)),
                ('lesionado', models.BooleanField(default=False)),
                ('jornadas_baja', models.PositiveSmallIntegerField(default=0)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='core.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('disputada', models.BooleanField(default=False)),
                ('fecha_simulada', models.DateField(blank=True, null=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='core.liga')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['liga', 'numero'],
                'unique_together': {('liga', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=10)),
                ('goles_max_goleador', models.PositiveIntegerField(default=0)),
                ('valoracion_mejor_jugador', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('campeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporadas_campeon', to='core.equipo')),
                ('subcampeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporadas_subcampeon', to='core.equipo')),
                ('max_goleador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporadas_goleador', to='core.jugador')),
                ('mejor_jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporadas_mejor', to='core.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.liga')),
            ],
            options={
                'verbose_name': 'Histórico de Temporada',
                'verbose_name_plural': 'Histórico de Temporadas',
                'ordering': ['-temporada'],
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.liga'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('temporada_inicio', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='core.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.liga')),
            ],
            options={
                'verbose_name': 'Mánager',
                'verbose_name_plural': 'Mánagers',
            },
        ),
        migrations.CreateModel(
            name='HistorialFichaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Fichaje'), ('V', 'Venta'), ('C', 'Cesión'), ('L', 'Agente libre')], default='F', max_length=1)),
                ('jornada', models.PositiveSmallIntegerField()),
                ('temporada', models.CharField(max_length=20)),
                ('exito', models.BooleanField(default=True)),
                ('equipo_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_entrada', to='core.equipo')),
                ('equipo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_salida', to='core.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_fichajes', to='core.jugador')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichajes', to='core.manager')),
            ],
            options={
                'verbose_name': 'Historial de Fichaje',
                'verbose_name_plural': 'Historial de Fichajes',
                'ordering': ['-jornada'],
            },
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('dificultad_fichaje', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('fecha_expiracion', models.PositiveSmallIntegerField(blank=True, help_text='Jornada en la que esta oferta expira', null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_mercado', to='core.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercado', to='core.liga')),
            ],
            options={
                'verbose_name': 'Oferta de Mercado',
                'verbose_name_plural': 'Mercado de Fichajes',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RES', 'Resultado'), ('FIC', 'Fichaje'), ('LES', 'Lesión'), ('REN', 'Renovación'), ('GEN', 'General')], default='GEN', max_length=3)),
                ('texto', models.TextField()),
                ('jornada', models.PositiveSmallIntegerField()),
                ('fecha_juego', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='core.manager')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-jornada', '-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(blank=True, max_length=100)),
                ('asistencia', models.PositiveIntegerField(default=0)),
                ('goles_local', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='core.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='core.equipo')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='core.jornada')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['jornada__numero'],
            },
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporadas_nuevas', models.PositiveSmallIntegerField(default=2)),
                ('nuevo_salario', models.PositiveIntegerField()),
                ('jornada', models.PositiveSmallIntegerField()),
                ('temporada', models.CharField(max_length=20)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='core.jugador')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='core.manager')),
            ],
            options={
                'verbose_name': 'Renovación',
                'verbose_name_plural': 'Renovaciones',
                'ordering': ['-jornada'],
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveSmallIntegerField(default=0)),
                ('partidos_jugados', models.PositiveSmallIntegerField(default=0)),
                ('partidos_ganados', models.PositiveSmallIntegerField(default=0)),
                ('partidos_empatados', models.PositiveSmallIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveSmallIntegerField(default=0)),
                ('goles_favor', models.PositiveSmallIntegerField(default=0)),
                ('goles_contra', models.PositiveSmallIntegerField(default=0)),
                ('puntos', models.PositiveSmallIntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='core.equipo')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='core.liga')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['-puntos', '-goles_favor', 'goles_contra'],
                'unique_together': {('liga', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_jugados', models.PositiveSmallIntegerField(default=0)),
                ('goles', models.PositiveSmallIntegerField(default=0)),
                ('asistencias', models.PositiveSmallIntegerField(default=0)),
                ('tarjetas_amarillas', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('tarjetas_rojas', models.PositiveSmallIntegerField(default=0)),
                ('valoracion', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='core.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='core.partido')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
                'unique_together': {('jugador', 'partido')},
            },
        ),
    ]
