# Generated by Django 6.0.3 on 2026-03-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
